# データ構造

すでに、[非常によくまとまった入門ガイド](https://github.com/bicycle1885/Julia-Tutorial/blob/master/Julia高速チュートリアル.ipynb)があるので、詳細はそちらを参照して欲しい。
ここでは、他の言語から移行する際に留意すべき点のみを記す。

## スカラ

スカラは単一のデータである（Juliaではスカラとは言わず、単一オブジェクトと呼ぶ）。
代表的なスカラは、数値、文字、文字列である。

### 数値

整数、浮動小数点数、複素数が利用できる。
ここでは整数と浮動小数点のみを扱う。
Juliaは、小数点なしの数値を整数、小数点付きを浮動小数点数として扱う。

In [1]:
# 整数型
(1+5)*6

36

In [2]:
# 浮動小数点数
(1.0+5.0)*6.0

36.0

数値を変数に代入できる。
その場合、変数も型を持つ。
変数の大文字と小文字は区別される。

In [3]:
# 整数の代入
a = 1

1

In [4]:
# 浮動小数点の代入
b = 1.0

1.0

それぞれの数値には、精度を規定する型がある。
デフォルトの整数型は`Int`（32ビットOSでは`Int32`、64ビットOSでは`Int64`）であり、浮動小数点型は`Float64`（倍精度実数）である。
とくに指示なく数値を利用するときは、この精度が自動的に使われる。
あるスカラの型をチェックするには `typeof()` 関数を使う。

In [5]:
# 整数型のチェック
typeof(1)

Int64

In [6]:
# 浮動小数点数型のチェック
typeof(1.0)

Float64

### 文字

Julia文字は、1つの文字や記号のみを意味する。
通常、文字を連ねた「文字列」を扱うが、文字はその構成単位である。
Juliaでは、シングルクーテーション `'` で囲んだ領域がUnicode文字として扱われる。

In [7]:
# 1個の x という文字
'x'

'x': ASCII/Unicode U+0078 (category Ll: Letter, lowercase)

文字の型名は `Char` である。

In [8]:
# 文字型のチェック
typeof('x')

Char

### 文字列

複数の文字が1列に連なったものを文字列という。
ダブルクオーテーション `"` で囲まれた領域が文字列として扱われる。

In [9]:
"abcde"

"abcde"

文字列の型名は `String` である。

In [10]:
# 文字列型のチェック
typeof("abcde")

String

文字列の各要素を読み出すには `[]` を利用する。
このカッコの中に、呼び出したい文字の位置を入れる（この位置は 1 からスタートする）。
切り出した結果は文字である（文字列ではない）。

In [11]:
# 3文字目を切り出す
"abcde"[3]

'c': ASCII/Unicode U+0063 (category Ll: Letter, lowercase)

切り出した部分を文字列として扱うには、`[]` の中に範囲を記入する。
範囲は `開始位置:終了位置` で規定する。
末尾を意味する特殊なキーワードとして `end` が利用できる。
範囲を省略し、`:`のみを使うと、全部の要素を指定することになる（`1:end`と同じ）。
以下の例を参照のこと。

In [12]:
# 結果は文字列になる
"abcde"[3:3]

"c"

In [13]:
# 3文字目から5文字目までを取り出す
"abcde"[3:5]

"cde"

In [14]:
# もちろん変数に対しても処理できる
s = "abcde"
s[3:5]

"cde"

In [15]:
# 最後の要素を意味する end が使える
s = "abcde"
s[3:end]

"cde"

文字列の処理は、後述する配列（ベクトル）の処理とほぼ同じである。

### スカラのまとめ

* 代表的なスカラ（単一オブジェクト）には、整数、浮動小数点、文字、文字列がある。
* 整数のデフォルト型は`Int`、浮動小数点のデフォルト型は`Float64`である。また、文字型は`Char`、文字列型は`String`である。
* スカラは変数に代入できる。その変数も、もとのスカラの型を引き継ぐ。
* 型をチェックするには `typeof()` 関数を利用する。
* 文字列から文字を取り出すには、文字列の末尾に `[]` を配置し、その中に位置番号を入れる（1からスタート）。得られるのは `Char` 型の文字である。
* 文字列から文字を取り出すには、`[]`内に範囲を記入する。範囲は `開始位置:終了位置` とする。1文字だけ取り出し、それを文字列にするには `開始位置:開始位置` とする。
* この`[]`内では、文字列の末尾の位置を意味する特殊キーワードの `end` が利用できる。
* 開始と終了位置を省略して `:` のみを使うと、全部の要素を指定することになる（`1:end`）。

## 配列

配列は、いくつかのスカラをひとまとまりにしたデータ構造である。
ここでは、1次元の配列をベクトル、2次元の配列を行列と呼ぶ。
配列には、実際にはどのようなデータ構造をも含めることができる。
たとえば、文字列のベクトル、ベクトルのベクトル、ベクトルの行列も作ることができる。
ここでは、単純に数値と文字列の配列のみを考慮する。

### ベクトル

ベクトルを作るには、要素をカンマ（`,`）で列挙して `[]` でくくる。 

In [16]:
# 整数型のベクトル
a = [1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

In [17]:
# 浮動小数点型のベクトル（整数と混合すると浮動小数点に揃えられる）
b = [1.0, 2, 3]

3-element Array{Float64,1}:
 1.0
 2.0
 3.0

In [18]:
# 文字列のベクトル（各文字列の長さが異なっていてもよい）
c = ["abcd", "efg", "hijkl"]

3-element Array{String,1}:
 "abcd" 
 "efg"  
 "hijkl"

後述するが、カンマを忘れると1行の行列になる。
Juliaでは「1行の行列」と「ベクトル」は明確に区別されるので、混同してはいけない。

In [19]:
# カンマを忘れて1行の行列になってしまった
aa = [1 2 3]

1×3 Array{Int64,2}:
 1  2  3

ベクトルの要素を取り出すには、ベクトルの末尾に`[]`を付加し、その中に要素番号を記入する。
要素番号（添え字）は1からスタートする（PerlやC言語などとは異なることに注意する）。
抜き出した要素は、スカラである。
文字列の配列は混乱しやすいので注意して記述する。

In [20]:
# 2個目の要素を抜き出す
a = [6, 7, 8]
a[2]

7

In [21]:
# 2番目の文字列を抜き出す
c = ["abcd", "efg", "hijkl"]
c[2]

"efg"

In [22]:
# 抜き出した文字列の2文字目と3文字目を取り出す
c[2][2:3]

"fg"

ベクトルの範囲を抜き出すには、ベクトルの末尾に `[]` を付加し、その中に範囲を記入する。
範囲は `開始位置:終了位置` として記入する。
この `[]` 内では、末尾の要素を意味するキーワード `end` が利用できる。
範囲を省略し、`:`のみを使うと、全部の要素を指定することになる（`1:end`と同じ）。
取り出した要素群も、ベクトルとして扱われる。

In [23]:
# 3番目から5番目の要素を抜き出す
x = [1, 2, 3, 4, 5]
x[3:5]

3-element Array{Int64,1}:
 3
 4
 5

In [24]:
# 末端要素を意味する end を使う
x[3:end]

3-element Array{Int64,1}:
 3
 4
 5

In [25]:
# 全部の要素を抜き出す
x[:]

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [26]:
# 複数の文字列を抜き出す
c = ["abcd", "efg", "hijkl"]
c[2:3]

2-element Array{String,1}:
 "efg"  
 "hijkl"

### 行列

データを2次元の表のように並べた構造を行列という。
ベクトルとは違い、行列には行（横方向のデータの並び）と列（縦方向のデータの並び）がある。
行を作るには要素をスペース区切りで列挙し、列を作るには行を`;`または改行で区切り、最後に全体を`[]`でくくる。
以下に整数の例を示すが、その他の型でも行列の作り方は同様である。

In [27]:
# 2行4列の行列
A = [1 2 3 4
     5 6 7 8]

2×4 Array{Int64,2}:
 1  2  3  4
 5  6  7  8

In [28]:
# 改行の代わりに `;` を利用できる。
A = [1 2 3 4; 5 6 7 8]

2×4 Array{Int64,2}:
 1  2  3  4
 5  6  7  8

In [29]:
# カンマで要素を区切るとエラーが発生する（ベクトルの要素指定とは異なる）
A = [1,2,3,4; 5,6,7,8]

LoadError: syntax: unexpected semicolon in array expression

行列の要素を取り出すのにも `[]` を利用するが、行と列を指定する2つの添え字が必要である；つまり `[行位置, 列位置]` である。
それぞれの位置には、範囲表記が利用出来る。
抜き出した要素群は、以下のように定義される。

* 抜き出した要素が単一ならば、スカラになる；例：`A[1,1]`。
* 抜き出した要素が1列行列または1行行列ならば、ベクトルになる；例：`A[:,1]`または`A[:,1]`。
* それ以外の場合、抜き出したものは行列になる。

In [30]:
# 特定の要素を抜き出す（結果はスカラ）
A = [1 2 3 4; 5 6 7 8]
A[1,3]

3

In [31]:
# 2行目を抜き出す（結果はベクトル）
A[2,:]

4-element Array{Int64,1}:
 5
 6
 7
 8

In [32]:
# 特定の範囲を抜き出す（結果は行列）
A[1:2,1:3]

2×3 Array{Int64,2}:
 1  2  3
 5  6  7

### 行列とベクトル（配列）のまとめ

* ベクトル（1次元配列）は要素を1列に並べたもの。行列（2次元配列）は要素を表形式に並べたもの。
* ベクトルに値を割つけるには、要素をカンマ区切りで並べて `[]` でくくる。
* 行列に値を割つけるには、1行内の要素の区切りとしてスペースを用い、列の区切りに改行または `;` を用い、さらに全体を `[]` でくくる。
* 配列の要素にアクセスするには、`[]` 内に要素の位置を入力する。行列の場合には、行番号と列番号をカンマで区切って入力する。
* 要素の範囲は `開始位置:終了位置` で指定する。特殊キーワード `end` は、その配列の最後の添え字を意味する。位置を省略して `:` を使うと、その方向の要素全部を指定したことになる（`1:end`）。
* 抜き出した要素の構造は、要素の指定によって異なる。抜き出した要素が単一ならスカラ、1行行列または1列行列ならベクトル、それ以外なら行列が得られる。

## ベクトルと行列の初期化

配列（ベクトルと行列）は、使用する前にメモリ領域を確保しなければならない。
上の例では、変数にベクトルや行列の全部の値を代入した。
この代入の時点で配列のサイズが確定し、メモリ確保が行われた。
こうすることで、配列の個々の要素にアクセスできた。

もしメモリ確保せず、配列の特定の要素に値を代入しようとするとエラーが発生する。

In [33]:
# 配列 newvec は事前にデータ割り当てされていない
# 特定の要素に値を代入しようとするとエラーになる
newvec[1] = 5

LoadError: UndefVarError: newvec not defined

### メモリ確保と初期化

配列の特定の要素に順に代入したい場合、まずはサイズを決め、メモリを確保しなければならない。
簡単な方法は、`zeros()`関数を使うことだ。
これは特定の大きさを持つ配列を定義し、その全要素をゼロで初期化する。
特定の型を指定して初期化することもできる。

In [34]:
# 5個の要素をもつベクトルを作り、ゼロで初期化する
# デフォルトでは Float64 になる
h = zeros(5)

5-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0

In [35]:
# 整数型 Int でベクトルを作る
h = zeros(Int,5)

5-element Array{Int64,1}:
 0
 0
 0
 0
 0

In [36]:
# 行数と列数を与えると、行列ができる（デフォルトでFloat64）
H = zeros(2,5)

2×5 Array{Float64,2}:
 0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0

In [37]:
# 整数型の行列もできる
H = zeros(Int,2,5)

2×5 Array{Int64,2}:
 0  0  0  0  0
 0  0  0  0  0

初期化関数は、ゼロで初期化する `zeros()` のほかにも、1で初期化する `ones()` や単位行列で初期化する `eye()` がある。

In [38]:
# 1で初期化する
H = ones(3)

3-element Array{Float64,1}:
 1.0
 1.0
 1.0

In [39]:
# 単位行列で初期化する
A = eye(3)

3×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

### メモリは確保するが初期化しない

非常に巨大な配列の場合、メモリ確保は必要だが、特定の値で初期化する必要がないケースがある。
Juliaでは、配列の型とサイズだけを与えて、メモリ確保だけできる。
ベクトルの確保には `Vector{型}(サイズ)` を、行列の確保には `Matrix{型}(行数,列数)` が利用できる。

In [40]:
# 整数型でサイズ 3 のベクトルを確保する
# 適当な値で初期化されている
a = Vector{Int}(3)

3-element Array{Int64,1}:
 0
 0
 0

In [41]:
# Float64で行列を確保する
# 適当な値で初期化されている
A = Matrix{Float64}(2,5)

2×5 Array{Float64,2}:
 1.65019e-153  3.98473e252  9.08367e223  4.05449e-317  0.0         
 2.18231e-94   1.4729e179   1.16466e-28  0.0           2.41499e-314

### ベクトルに要素を追加する

実は、ユーザーは、ベクトルに値を自由に「追加」できる（行列の場合は別の考え方が必要になるので、ここでは省略する）。
この場合、最初にサイズ不定の空っぽのベクトルを用意し、そこに値を追加する；この場合、値は配列の末尾に順次追加されていく。
これはベクトルを可変長の一時領域として使う場合に便利である。
末尾への値の追加は `push!()`、末尾の値の削除は `pop!()`、先頭への値の追加は `unshift!()`、先頭の値の削除は `shift!()` で行う。

In [42]:
# 空っぽのベクトルを準備する
v = Vector{Int}()

0-element Array{Int64,1}

In [43]:
# 値を順に追加する
push!(v,3);
push!(v,5);
push!(v,7);
v

3-element Array{Int64,1}:
 3
 5
 7

In [44]:
# 最後の要素を除去する
# 除去した値を受けとることもできる（不要ならば、以下の変数 a は省力できる）
a = pop!(v);
v

2-element Array{Int64,1}:
 3
 5

In [45]:
# 先頭に値を追加する
unshift!(v,1)

3-element Array{Int64,1}:
 1
 3
 5

In [46]:
# 先頭から値を除去する
# 除去した値を受け取ることもできる（不要ならば、以下の変数 a は省略できる）
a = shift!(v)
v

2-element Array{Int64,1}:
 3
 5

### 初期化のまとめ

* 配列の個々の要素にアクセスする前に、必要なメモリを確保しておく必要がある。
* メモリ確保とゼロ初期化を同時に行う関数が `zeros()` である。ベクトルと行列の両方に対応している。
* メモリを確保するが、初期化の必要がない場合には、ベクトルに関して `Vector{型}(要素数)`、行列に関して `Matrix{型}(行数,列数)` が利用出来る。初期値として適当な数字が入っている。
* ベクトルへのデータ追加・除去だけを行う場合には、事前にサイズを確保しておく必要はない。空っぽのベクトルを `Vector{型}()` で宣言し、先頭または末尾に要素を追加／先頭または末尾から要素を除去する関数を使う。
